### ISSUE TITLE
Check

### ISSUE THREAD

**Issue by seferen** [Sharpovich/AutoRepPerfTool#4]
Add check configs

**Comment by Sharpovich** [comment]
Не совсем вкурил суть требования, о каких конфигах речь

**Comment by Sharpovich** [comment]
Если конфиг заполнен полностью, то так, если не полностью, то иначе

**Comment by seferen** [comment]
Нет, проверка на то что ты получил валидный ождаемый конфиг в url например, или что у тебя действительно на этом урле есть grafana или еще что то в этом духе
